Pequiven\SEIPBundle\Entity\Sip\OnePerTen:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [id]
        cedula:
            expose: true
            groups: [api_list]
        user:
            expose: true
            groups: [api_list]
#        nombre:
#            expose: true
#            groups: [api_list]
#        centro:
#            expose: true
#            groups: [api_list]
#        codigoCentro:
#            expose: true
#            groups: [api_list]
#        municipio:
#            expose: true
#            groups: [api_list]
#        parroquia:
#            expose: true
#            groups: [api_list]