Pequiven\ArrangementProgramBundle\Entity\ArrangementProgram:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [id]
        ref:
            expose: true
            groups: [api_list]
        type:
            expose: true
            groups: [api_list]
        period:
            expose: true
            groups: [period]
        categoryArrangementProgram:
            expose: true
            groups: [api_list]
        tacticalObjective:
            expose: true
            groups: [tacticalObjective]
        operationalObjective:
            expose: true
            groups: [operationalObjective]
        process:
            expose: true
            groups: [api_list]
        createdBy:
            expose: true
            groups: [api_list]
        status:
            expose: true
            groups: [api_list]
        details:
            expose: true
            groups: [details]
        progressToDate:
            expose: true
            groups: [api_result] 
        description: 
            expose: true
            groups: [api_list]