#ORDENES DE PEDIDO POR KIT
pequiven_housesupply_orderkit_charge:
    path: /createOrderKit/{typemember}
    defaults:
        _controller: pequiven.controller.housesupply_orderkit:chargeAction
        _format: html
    requirements:
        _format: html|json|xml
    methods: [GET|POST]
    
pequiven_housesupply_orderkit_show:
    path: /showOrderKit/{id}
    defaults:
        _controller: pequiven.controller.housesupply_orderkit:showAction
        _format: html
    requirements:
        _format: html|json|xml
    methods: [GET|POST]
    
pequiven_housesupply_orderkit_register:
    path: /registerOrderKit/
    defaults:
        _controller: pequiven.controller.housesupply_orderkit:registerAction
        _format: html
    requirements:
        _format: html|json|xml
    methods: [GET|POST]
    
pequiven_housesupply_orderkit_charge_total:
    path: /totalOrderKit/
    defaults:
        _controller: pequiven.controller.housesupply_orderkit:totalAction
        _format: html
    requirements:
        _format: html|json|xml
    methods: [GET|POST]

#VALIDACIÃ“N DE ORDENES DE PEDIDO
pequiven_housesupply_orderkit_check:
    path: /checkOrderKit/
    defaults:
        _controller: pequiven.controller.housesupply_orderkit:checkAction
        _format: html
    requirements:
        _format: html|json|xml
    methods: [GET|POST]
    
pequiven_housesupply_orderkitcheck_edit:
    path: /addMemberOrderKit/
    defaults:
        _controller: pequiven.controller.housesupply_orderkit:editMemberOrderCheckAction
        _format: html
    requirements:
        _format: html|json|xml
    methods: [GET|POST]

#PAGOS DE ORDENES DE PEDIDO
pequiven_housesupply_orderkitcheck_payment:
    path: /paymentOrderKit/
    defaults:
        _controller: pequiven.controller.housesupply_orderkit:PaymentOrderCheckAction
        _format: html
    requirements:
        _format: html|json|xml
    methods: [GET|POST]
    
#ORDENES DE PEDIDO POR PRODUCTO    
pequiven_housesupply_order_charge_add:
    path: /addItemOrderKit/
    defaults:
        _controller: pequiven.controller.housesupply_order:addItemAction
        _format: html
    requirements:
        _format: html|json|xml
    methods: [GET|POST]
    
pequiven_housesupply_order_charge_delete:
    path: /deleteItemOrderKit/{id}
    defaults:
        _controller: pequiven.controller.housesupply_order:deleteItemAction
        _format: html
    requirements:
        _format: html|json|xml
    methods: [GET|POST]
   
    
    

