pequiven_seip_arrangementprogram_by_gerencia:
    path: /{typeGroup}/{idGerencia}.{_format}
    defaults:
        _controller: pequiven_seip.controller.arrangementprogram:arrangementProgramByGerenciaAction
        _format: html
    requirements:
        _format: html|json|xml
    methods: [GET]

pequiven_seip_arrangementprogram_all:
    path: /all/.{_format}
    defaults:
        _controller: pequiven_seip.controller.arrangementprogram:listAllAction
        _format: html
    requirements:
        _format: html|json|xml
    methods: [GET]
    
pequiven_seip_sig_arrangementprogram_all:
    path: /sig/.{_format}
    defaults:
        _controller: pequiven_seip.controller.arrangementprogram:listSigAllAction
        _format: html
    requirements:
        _format: html|json|xml
    methods: [GET]
pequiven_seip_sig_arrangementprogram_all_managementSystem:
    path: /sig-management/.{_format}
    defaults:
        _controller: pequiven_seip.controller.arrangementprogram:listSigManagementAction
        _format: html
    requirements:
        _format: html|json|xml
    methods: [GET]