## YAML Template.
pequiven_master_home:
    path: /adminMaster/{type}/{action}
    defaults: {_controller: PequivenMasterBundle:Master:showHome}
    methods: [GET]

select_gerenciaFromComplejo:
    path: /adminMaster/select_gerenciaFromComplejo
    defaults:
        _controller: PequivenMasterBundle:Master:selectGerenciaFirstFromComplejo
        
#Devuelve el paginador con la data de las gerencias de 1ra línea
gerenciaFirstList:
    path: /adminMaster_list/gerenciaFirst
    defaults: 
        _controller: pequiven.controller.gerenciafirst:gerenciaFirstListAction
        _sylius:
            method: createPaginatorGerenciaFirst

#Devuelve el paginador con la data de las gerencias de 2da línea
gerenciaSecondList:
    path: /adminMaster_list/gerenciaSecond
    defaults: 
        _controller: pequiven.controller.gerenciasecond:gerenciaSecondListAction
        _sylius:
            method: createPaginatorGerenciaSecond
            
pequiven_gerenciafirst:
    resource: "@PequivenMasterBundle/Resources/config/routing/gerenciafirst.yml"
    prefix: /master/gerencia-first
#Devuelve el paginador con la data de las gerencias de 2da línea
admin_master_configuration_notify:
    path: /configuration/notify
    defaults: 
        _controller: pequiven.controller.configuration:indexAction
pequiven_configurations_get_to_programs:
    path: /program-get-to-data.{_format}
    defaults:
        _controller: pequiven.controller.configuration:getProgramAction
        _format: json
    requirements:
        _format: json
    methods: [GET|POST]
    options:
        expose: true
pequiven_configuration_find_data:
    path: /find-data-users.{_format}
    defaults:
        _controller: pequiven.controller.configuration:findByDataAction
        _format: json
    requirements:
        _format: json
    methods: [GET|POST]
    options:
        expose: true
pequiven_configuration_get_data_users:
    path: /get-data-users
    defaults: 
        _controller: pequiven.controller.configuration:getDataUsersAction