Pequiven\IndicatorBundle\Entity\Indicator:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [id]
        createdAt:
            expose: true
            groups: [api_list]
        updatedAt:
            expose: true
            groups: [api_details]
        userCreatedAt:
            expose: true
            groups: [api_details]
        userUpdatedAt:
            expose: true
            groups: [api_details]
        description:
            expose: true
            groups: [api_list]
        ref:
            expose: true
            groups: [api_list]
        refParent:
            expose: true
            groups: [api_list]
        tmp:
            expose: true
            groups: [api_list]
        weight:
            expose: true
            groups: [api_list]
        goal:
            expose: true
            groups: [api_list]
        valueFinal:
            expose: true
            groups: [api_list]
        indicatorLevel:
            expose: true
            groups: [api_details]
        objetives:
            expose: true
            groups: [objetives]
        tendency:
            expose: true
            groups: [tendency]
        formula:
            expose: true
            groups: [formula]
        period:
            expose: true
            groups: [period]
        valuesIndicator:
            expose: true
            groups: [valuesIndicator]
        progressToDate:
            expose: true
            groups: [resultIndicator]
        resultReal:
            expose: true
            groups: [resultIndicator]
        arrangementRange:
            expose: true
            groups: [arrangementRange]
        featuresIndicator:
            expose: true
            groups: [featuresIndicator]
        managementSystems:
            expose: true
            groups: [managementSystems]
        indicatorlast:
            expose: true
            groups: [indicatorlast]
        indicatorCause:
            expose: true
            groups: [indicatorCause]
        
        
