pequiven_sig_homepage:
    path:     /hello/{name}
    defaults: { _controller: PequivenSIGBundle:Default:index }
#Listado general de objetivos marcados con magementsystem
pequiven_objetives_list_sig:
    path: /sig/{level}/list.{_format}
    defaults:
        _controller: pequiven.controller.managementsystem_sig_objetives:ObjetiveslistAction
        _format: html
    requirements:
        _format: html|json|xml
        level: 1|2|3
    methods: [GET]
#listado de matriz de objetivos
pequiven_objetives_gerencia_list_sig:
    path: /adminMaster/list/sig.{_format}
    defaults:
        _controller: pequiven.controller.managementsystem_sig_objetives:listAction
        _format: html
    requirements:
        _format: html|json
    methods: [GET]
    options:
        expose: true
#Devuelve el paginador con la data de las gerencias de 1ra línea
pequiven_objetives_gerencia_list_:
    path: /adminMaster_list/gerenciaFirst
    defaults: 
        _controller: pequiven.controller.gerenciafirst:gerenciaFirstListAction
        _sylius:
            method: createPaginatorGerenciaFirst
#export matriz managementesystem
pequiven_sig_gerenciafirst_export:
    path: /adminMaster/list/{id}/export
    defaults: { _controller: pequiven.controller.managementsystem_sig_objetives:exportAction }
    requirements:
        id: "\d+"
    methods: [GET]
    options:
        expose: true
#listado de sistemas de la calidad para lista de seguimiento
pequiven_sig_monitoring_list:
    path: /sig/monitoring/list.{_format}
    defaults:
        _controller: pequiven.controller.monitoring_sig:listAction
        _format: html
    requirements:
        _format: html|json
    methods: [GET]
    options:
        expose: true
pequiven_sig_monitoring_show:
    path: /sig/monitoring/{id}
    defaults:
        _controller: pequiven.controller.monitoring_sig:showAction
        _format: html    
    methods: [GET]
pequiven_sig_monitoring_export:
    path: /sig/export/{id}
    defaults:
        _controller: pequiven.controller.monitoring_sig:exportAction
        _format: html    
    methods: [GET]
#Seguimiento a Carga de informes de evolución
pequiven_indicator_evolution_load:
    path: /indicator/sig/load
    defaults: 
        _controller: pequiven.controller.indicator_sig:loadAction

